In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']

# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)


# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[30, 30], [16, 25], [17, 44], [20, 25], [43], [17], [34, 44], [48, 16], [34, 25], [49, 31, 30, 15]]
[[30 30  0  0]
 [16 25  0  0]
 [17 44  0  0]
 [20 25  0  0]
 [43  0  0  0]
 [17  0  0  0]
 [34 44  0  0]
 [48 16  0  0]
 [34 25  0  0]
 [49 31 30 15]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
Accuracy: 100.000000


In [ ]:
len(model.get_weights()) # 3 because 3 layers.

3

In [ ]:
model.get_weights()[0].shape # weights of embedding
# 50 words and output vector of 8

(50, 8)

In [ ]:
model.get_weights()[0]

array([[ 0.05133361,  0.01514427,  0.08074942, -0.04129414,  0.03030681,
         0.01738363, -0.01646128, -0.07771827],
       [ 0.01229091, -0.01239631,  0.03169588,  0.01230127, -0.03703195,
         0.03260769, -0.02261551,  0.00104643],
       [-0.00454088, -0.00200701, -0.02168166,  0.00197184, -0.04925796,
         0.0184604 , -0.04166036,  0.00207586],
       [-0.03084027,  0.01909396, -0.03614576,  0.0104425 , -0.02396097,
        -0.00065243,  0.02109274,  0.04264482],
       [ 0.02135142, -0.01752476, -0.04731572,  0.02206513,  0.03975532,
         0.02373991, -0.02998352, -0.02876381],
       [-0.03585364,  0.00161831,  0.00101936, -0.01483341,  0.00710689,
        -0.02857107,  0.00273716,  0.03748261],
       [-0.00894002,  0.03700501,  0.03386292,  0.02416309,  0.01401779,
         0.04706998,  0.0385999 ,  0.03973434],
       [-0.0292569 , -0.04872965,  0.02427863, -0.01564193,  0.03460992,
         0.02574285,  0.01047063,  0.01576691],
       [-0.00597874, -0.04521991

In [ ]:
layer_names = []
for layer in model.layers:
    print(layer.name)
    layer_names.append(layer.name)

embedding_1
flatten_1
dense_1


In [ ]:
import keras
intermediate_layer_model = keras.Model(inputs=model.input,
                                       outputs=model.get_layer(layer_names[0]).output)

intermediate_output = intermediate_layer_model([15])
intermediate_output

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-0.0956243 , -0.06389374, -0.09089544,  0.09732154, -0.08546121,
       -0.07689027,  0.03592177,  0.07462851], dtype=float32)>

In [ ]:
model.get_weights()[0][15]

array([-0.0956243 , -0.06389374, -0.09089544,  0.09732154, -0.08546121,
       -0.07689027,  0.03592177,  0.07462851], dtype=float32)

In [ ]:
intermediate_output = intermediate_layer_model(array([[0,1]]))

In [ ]:
intermediate_output

<tf.Tensor: shape=(1, 2, 8), dtype=float32, numpy=
array([[[ 0.05133361,  0.01514427,  0.08074942, -0.04129414,
          0.03030681,  0.01738363, -0.01646128, -0.07771827],
        [ 0.01229091, -0.01239631,  0.03169588,  0.01230127,
         -0.03703195,  0.03260769, -0.02261551,  0.00104643]]],
      dtype=float32)>

In [ ]:
model.get_weights()[0][13]

array([-0.04074562, -0.01054851,  0.03409232, -0.01765499,  0.01825703,
       -0.04914978, -0.02708818,  0.04321686], dtype=float32)

In [ ]:
model.get_weights()[0][15]

array([-0.0956243 , -0.06389374, -0.09089544,  0.09732154, -0.08546121,
       -0.07689027,  0.03592177,  0.07462851], dtype=float32)